### ISSUE TITLE
General question about numerical types used in wavelet calculation: Is double precision important or would single precision suffice? We could inherit precision from the input array.

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#245]
General question about numerical types used in wavelet calculation: Is double precision important or would single precision suffice? We could inherit precision from the input array.

_Originally posted by @milancurcic in https://github.com/Cloud-Drift/clouddrift/issues/240#issuecomment-1701442238_

**Comment by selipot** [comment]
For the wavelet stuff, @jonathanlilly states that things eventually become delicate so that double precision can be advocated for. We should discuss strategy in terms of inheritance, enforcement, and need.

Also, what is really the list of standard dtype for numpy and python? See as an example https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.double which suggests that `complex128` is for linux only??

**Comment by milancurcic** [comment]
OK, let's be defensive then and just do everything double. Just wanted to make sure it's intentional.

I didn't know these were Linux specific aliases. I find that confusing. If there's an OS agnostic name, why even have an OS specific alias? Anyway, let's just go with what the docs recommended and disregard my comment on this.

**Comment by milancurcic** [comment]
Let's continue the discussion back in the wavelet PR to keep info in one place.
