### ISSUE TITLE
Upgrade to awkward v2

### ISSUE THREAD

**Issue by milancurcic** [Cloud-Drift/clouddrift#55]
Awkward v2 was released on [Dec 9](https://github.com/scikit-hep/awkward/releases/tag/v2.0.0). As we don't require `<2` for `awkward` in pyproject.toml `dependencies` field, the `awkward` import will need to change from

```python
import awkward._v2 as ak
``` 

to

```python
import awkward as ak
```

and require `awkward>=2.0.0` in pyproject.toml.

Thanks to Ibis Gonzalez for reporting.

**Comment by philippemiron** [comment]
Just to be clear, how things are implemented in Clouddrift, it would not work without the syntax implemented in v2. There were supposed to support using `import awkward._v2` for a while (https://github.com/scikit-hep/awkward/issues/1729), but it looks like they recently decided otherwise (https://github.com/scikit-hep/awkward/issues/1771).

**Comment by selipot** [comment]
Just went through an install of clouddrift with pip in a basic environment and the subsequent `import clouddrift` fails because of that. Let's fix this.
