### ISSUE TITLE
Function to recast longitude values [0,360] or [-180,180]

### ISSUE THREAD

**Issue by selipot** [Cloud-Drift/clouddrift#63]
lon = longitude_unwrap(lon,pivot=[180,360]) : recast longitudes in [-180,180[ or or [0,360[
See in jLab deg180.m, deg360.m and inversion degunwrap.m

**Comment by philippemiron** [comment]
This is what I used, it's very simple but might be useful.

```
@nb.jit
def deg360(lon):
    """Convert longitude array from [-180, 180] to [0, 360]"""
    return np.mod(lon, 360)
```

```
@nb.jit
def deg180(lon):
    """Convert longitude array from [0, 360] to [-180, 180]"""
    return deg360(lon + 180) - 180
```

**Comment by jonathanlilly** [comment]
It may be occasionally useful to unwrap longitude not starting at 0 or -180.  For example, sometimes I like to start at 20°00 East, the southern tip of Africa, as this avoids cutting the major ocean basins.

The following Matlab code will take longitude x in -180:180 or 0:360 and return it so that it ranges from lono to 360+lono.  

x=deg360(frac(360,2*pi)*unwrap(angle(rot(frac(2*pi,360)*(x-lono)))))+lono

the function rot is define as rot(x)=exp(ix); 

Thus, choose lono=-180 to convert to -180:180 or lono=0 to convert to 0:360.

**Comment by milancurcic** [comment]
https://github.com/Cloud-Drift/clouddrift/issues/63#issuecomment-1367428773 seems to me the way to go, one general function rather than 180- or 360-specific ones.
